version: '3.7'
services:
  db:
    image: mysql:8
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_bin'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
